<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZjtBSyN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZjtBSyN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZjtBSyN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZjtBSyN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZjtBSyN\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZjtBSyN',
    'container.build_id' => '4dfeb351',
    'container.build_time' => 1681681988,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZjtBSyN');
